import Head from 'next/head';
import { Home } from '@app/components/Home';
import { GetServerSideProps } from 'next';
import AnimeServices from '@app/services/Anime';
import { HomeProps } from '@app/components/Home/Home.types';

export default function HomePage({ trendingAnimes, categories, animesByCategory }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Animes Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home
        trendingAnimes={trendingAnimes}
        categories={categories}
        animesByCategory={animesByCategory}
      />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const responseCategory = await AnimeServices.listAnimeCategories();

  const animesByCategoryPromises = responseCategory.map((category) => {
    return AnimeServices.listAnimesByCategories(category.id);
  });

  const animesResponse = await Promise.all([
    AnimeServices.listTrending(),
    ...animesByCategoryPromises,
  ]);

  const trendingAnimes = animesResponse.shift();

  return {
    props: {
      trendingAnimes,
      animesByCategory: animesResponse,
      categories: responseCategory,
    },
  };
};
