import Head from 'next/head';
import { Home } from '@app/components/Home';
import { GetServerSideProps } from 'next';
import AnimeServices from '@app/services/Anime';
import { HomeProps } from '@app/components/Home/Home.types';

export default function HomePage({ trendingAnimes, highlightedAnine }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Animes Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home trendingAnimes={trendingAnimes} highlightedAnine={highlightedAnine} />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const response = await AnimeServices.listTrending();

  return { props: { trendingAnimes: response, highlightedAnine: response[0] } };
};
