import Head from 'next/head';
import { Home } from '@app/components/Home';

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Animes Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  );
}
